### PR TITLE
Test: Call Python from an admin PowerShell for IS decryption

### PR DESCRIPTION
**Pull request by Nutzzz**
1. The current method isn't great, as it:
- [x] requires Python to be in the path, with the appropriate libraries installed [FIXED: now using Python in GOG install directory], and
- [x] a UAC prompt will come up every time GOG is opened.  Should we not do a search every time?  See 2 below.
- [ ] We also don't know when execution is returned, and I'm only giving 10 seconds for the user to agree and files to be processed before attempting to check the result.
2. Perhaps we could:
- [ ] add a Metadata Import button to Features, and perform this check then.  Not sure whether games will be refreshed afterwards though.
3. This is still crashing for me at this point, as
- [x] I'm getting two copies of the decrypted IS in %TEMP%\is.json, and the trailing characters are now in the middle. [FIXED]
- [x] New crash: Premature EOF in get_capabilities? [FIXED]

### CODE REVIEW

**Comment by Nutzzz** [comment]
FYI, regarding 1 above, using [pyuac](https://pypi.org/project/pyuac/) allows data to be returned from the new admin window, but of course this method has the same problem trying to access Windows dlls that make [WMI](https://pypi.org/project/WMI/) not work.

**Comment by BellezaEmporium** [comment]
Hmm... I guess we'll have to do with the current things then. Managed to sort out the WMI issue by rewriting the logic, but now I need to make the decryption work flawlessly. Right now it's a space issue (my CPU name had spaces after, but my actual implementation removes them while it shouldn't). Working on it.

**Comment by Nutzzz** [comment]
> Of course, right now, we also cannot load the IS file directly from EA Desktop's files, as it requires administrator rights. Sadly, i don't think running Galaxy as administrator will give the Python env. the same rights.

Sorry if that wasn't clear, but that's exactly what this PR does.  It uses PowerShell to open python.exe from the %path% with admin rights.

Rather than relying on the user to do the legwork to make sure their Python is set up correctly, with the correct version, in the %path%, etc., I'm trying to figure out if we can use <gog-install-dir>\python\python.exe instead (after retrieving the location from the registry).  However, the cryptography library is obviously not included, and the import isn't working, this would require rolling our own AES decryption.  I've been experimenting with the relatively minimal version [here](https://github.com/ricmoo/pyaes) and paring it down further.

**Comment by Nutzzz** [comment]
OK, it's getting close (Half of 1, and 3 above are complete), but it's still reporting a crash, though at this point the plugin log is not giving a traceback.

**Comment by BellezaEmporium** [comment]
Will check.

**Comment by BellezaEmporium** [comment]
Managed to make your part work with mine. IS is being decrypted successfully, though now Galaxy's JSONRPC answers with EOF over Capabilities.

**Comment by BellezaEmporium** [comment]
Will push my part onto the dev branch. It'll permit you to check.

**Comment by BellezaEmporium** [comment]
Well, seems like i've corrected the issue. The dev plugin now works.

**Comment by Nutzzz** [comment]
Unfortunately, my single NVIDIA-only VideoController config is not working with your latest.  Since data.get('PNPDeviceID') returns a string and not an array of strings, data.get('PNPDeviceID')[0] just returns the first character.

**Comment by Nutzzz** [comment]
Won't the json file need to be updated occasionally?

**Comment by BellezaEmporium** [comment]
> Won't the json file need to be updated occasionally?

Fixed the WMIC issue.
Well... thought about it at first. This would need a hook under the IS file. If the filesize changes, this means a new entry has been created. We could write a file named "is_filesize" that looks after the IS file size.

**Comment by Nutzzz** [comment]
> We could write a file named "is_filesize" that looks after the IS file size.

Or even better, store it in the persistent_cache?  See, e.g. https://github.com/tylerbrawl/Galaxy-Utils/blob/master/docs/src/time_tracker.rst
which stores its data in a file and the cache.  In this case, I think the cache alone would be sufficient.

**Comment by Nutzzz** [comment]
> Fixed the WMIC issue. 

Confirmed: It works for me now.

**Comment by Nutzzz** [comment]
Also, it would be good to invalidate the .json file somehow if an exception occurs, so the next time GOG is launched it can attempt the scan again.  For instance, I suspect there may be other possible trailing characters besides the 2 we ran across.  I'd suggest it be renamed in that case so it can be retrieved for troubleshooting purposes.

**Comment by BellezaEmporium** [comment]
> Also, it would be good to invalidate the .json file somehow if an exception occurs, so the next time GOG is launched it can attempt the scan again. For instance, I suspect there may be other possible trailing characters besides the 2 we ran across. I'd suggest it be renamed in that case so it can be retrieved for troubleshooting purposes.

Good point, will check that when I can.

**Comment by Nutzzz** [comment]
Note I still have to disconnect and reconnect after closing and re-opening GOG for things to get working properly again.

**Comment by Nutzzz** [comment]
> For instance, I suspect there may be other possible trailing characters besides the 2 we ran across.

Y'know, maybe we can just drop the last x bytes... or anything found after the last closing brace?

**Comment by BellezaEmporium** [comment]
> > For instance, I suspect there may be other possible trailing characters besides the 2 we ran across.
> 
> Y'know, maybe we can just drop the last x bytes... or anything found after the last closing brace?

I'm currently tackling this and the IS filesize caching. I've put it as WIP as i'm quite unsure about the working state of the plugin rn, will check in dev later on.

**Comment by BellezaEmporium** [comment]
Got back onto it. IS file caching should work, as i've put the logic after the handshake with the GoG Galaxy client is complete. Logging works too, now tackling the usage of the IS.json (decrypted IS file) instead of using any other method.

Filtering the decrypted data to remove all junk should work too.

**Comment by BellezaEmporium** [comment]
As for the token being invalid, it's actually the EA API call to "pids/me" that's often rejected. Since I do not know the duration of a token, apart of trying to refresh it, it's like finding a needle in a haystack.

**Comment by ABaumher** [comment]
If it's like the tokens steam users (or for that matter, most oauth logins), it's just json and you can pull the duration from it with a bit of parsing. Iirc steam has a number of milliseconds that the token is good for. admittedly, our approach is just use it until it times out; steam actually doesn't follow proper access/refresh token rules and the access token lasts roughly seven months.

**Comment by BellezaEmporium** [comment]
> If it's like the tokens steam uses (or for that matter, most oauth logins), it's just json - a 64 character access id, and then some metadata - and you can pull the duration from it with a bit of parsing. Iirc steam has a number of milliseconds that the token is good for. admittedly, our approach is just use it until it times out; steam actually doesn't follow proper access/refresh token rules and the access token lasts roughly seven months.

I could check that out actually, since it's a JWT token. All the info are there when read.

**Comment by BellezaEmporium** [comment]
Following the recent findings, closing this PR :)

**Pull request closed without merging**
