### PR TITLE
A couple of small changes to the dev branch

### PR DESCRIPTION
**Pull request by Nutzzz**

### CODE REVIEW

**Comment by BellezaEmporium** [comment]
For the 'PNPDeviceID', i must say it was the only way (on my side) to make it correspond to my string (as it weirdly prompted my NVidia GPU display, not my AMD CPU one). Thus the key was incorrect on arrival.

**Comment by Nutzzz** [comment]
Hm... Well in my case, I don't have a built-in GPU, so it fails on my machine.

**Comment by BellezaEmporium** [comment]
> Hm... Well in my case, I don't have a built-in GPU, so it fails on my machine.

It should (normally) point the Intel or AMD PNP ID. Rather odd to say the least. I'll check.

**Comment by Nutzzz** [comment]
Right, but my *only* adapter is NVIDIA.

**Comment by BellezaEmporium** [comment]
> Right, but my _only_ adapter is NVIDIA.

Ah ! Now that's something I haven't thought of. Then i'll add an "elif" that'll get the NVIDIA PNP ID *only* if it's the main display.

**Comment by Nutzzz** [comment]
My method should do that.  It collects all of them, and breaks out of the loop if an Intel or AMD is found.

**Comment by BellezaEmporium** [comment]
> My method should do that. It collects all of them, and breaks out of the loop if an Intel or AMD is found.

Well, my "main" display is AMD, so if I accept this, it won't work for me.

**Comment by Nutzzz** [comment]
Maybe I'm confused.  Whatever the last one found should control.  If you had two AMDs, it might pick the wrong one.

**Comment by Nutzzz** [comment]
Closing in favor of #2

**Pull request closed without merging**
